### ISSUE TITLE
Missing/no info on pxegrub.pxe when using --dhcp-tftp

### ISSUE THREAD

**Issue by alberand** [wentasah/novaboot#8]
Isn't `pxegrub.pxe` missing in the repo? https://github.com/wentasah/novaboot/blob/master/novaboot#L1132

Found it here https://github.com/TUD-OS/NUL/blob/master/michal/boot/pxegrub.pxe not sure about the nature of this binary/where it comes from

**Comment by wentasah** [comment]
You're right. `pxegrub` was some patched version of GRUB1, that was capable of loading things via PXE. I think that today, you can achieve the same with GRUB2 or with other bootloaders like pxelinux. If you just want to boot Linux on x86 hardware, I guess that pxelinux would be most straightforward.

I think that today, it doesn't make sense to keep support for pxegrub in novaboot. Currently, I don't have any need for it or any replacement, but if you want to find some working solution with pxelinux (or whatever else), I'll happily merge it to novaboot.

In addition, this option currently works only with x86 architecture (because pxegrub was x86-only). It would be useful to extend it so that it works with multiple bootloaders and other architectures.

I don't know what are your needs, but if you write what you need, I'll try to help with implementing something that works.

**Comment by alberand** [comment]
Cool, yep x86, will look into what can I do with pxelinux

**Comment by wentasah** [comment]
#9 was merged so I'm closing this too.
